In [13]:
def swap(c):
  original_list=list(c) # This creates a copy of the list c, which is called original_list.  Your function should work with this list instead of the list c which is passed to the function.
  swapped_list=original_list.copy()
  swapped_list[0]=original_list[-1]
  swapped_list[-1]=original_list[0]
  # Put your code here, which should correctly redefine the value of the list swapped_list.  We've already set up the return statement for you.
  return swapped_list

swap(["asdf",9.88,1,"true",0])

[0, 9.88, 1, 'true', 'asdf']

In [0]:
def absolute_value(x):
  if x<0:
    abs_val=-x
  else:
    abs_val=x
  # Put your code here, which should correctly redefine the value of the variable abs_value.  We've already set up the return statement for you.
  return abs_val

In [20]:
print(absolute_value(-9))
print(absolute_value(8))
print(absolute_value(0))
print(absolute_value(8))

9
8
0
8


In [0]:
def indicator(lower,upper,n):
  ind_val=(lower <= n <= upper)
  # Put your code here, which should correctly redefine the value of the variable ind_val.  We've already set up the return statement for you.
  return ind_val

In [25]:
print(indicator(-9,2,0))
print(indicator(-0,0,0))
print(indicator(-9,2,-0))
print(indicator(-9,-2,0))
print(indicator(2,2,2))

True
True
True
False
True


In [0]:
def trunc_max(x,y):
  tm_val=max(0,x,y)
  # Put your code here, which should correctly redefine the value of the variable tm_val.  We've already set up the return statement for you.
  return tm_val

In [28]:
print(trunc_max(-9,3))
print(trunc_max(9,3))
print(trunc_max(-9,-3))
print(trunc_max(0,0))

3
9
0
0


In [0]:
def middle(c):
  middle_list=c[1:-1]
  # Put your code here, which should correctly redefine the value of the list middle_list.  We've already set up the return statement for you.
  return middle_list


In [31]:
middle([1,2,3,4,5,6,7])

[2, 3, 4, 5, 6]

In [32]:
for j in range(10,26,5):
  print(j)

10
15
20
25


In [33]:
for j in range(100,13,-7):
  print(j)

100
93
86
79
72
65
58
51
44
37
30
23
16


In [37]:
my_list=[100,-3.14,42,-1]
for j in my_list:
  print(j)
print(my_list)
my_list

100
-3.14
42
-1
[100, -3.14, 42, -1]


[100, -3.14, 42, -1]

In [39]:
my_list=[1,2,3,4]
for i in my_list:
  i=2*i
  print(i)
  
my_list

2
4
6
8


[1, 2, 3, 4]

In [0]:
def sum_list(L):
  sum=0
  for i in range(len(L)):
    sum=sum+L[i]
  return sum

In [44]:
sum_list([1,2,3,4])

10

In [0]:
def list_relu(L):
  new_list=L
  for i in range(len(new_list)):
    if new_list[i]<0:
      new_list[i]=0
  return new_list

In [47]:
print(list_relu([3,2,-9,-8,-7,0]))

[3, 2, 0, 0, 0, 0]


In [0]:
import numpy as np

In [51]:
my_var=(np.exp(5)-np.log(np.sqrt(5)))/(np.exp(np.cos(3)))   # Replace the value of 0 with the required value from Problem 4.
print(my_var)

397.24594182538


In [52]:
v=np.array([1,3,-2,4,5])
u=np.array([1,1,-2,1,1])
w=np.array([1,0,1,0,1])
my_vect_var=np.array((np.dot(v,u)/np.dot(u,u))*u+(np.dot(v,w)/np.dot(w,w))*w)

my_vect_var

array([ 3.45833333,  2.125     , -2.91666667,  2.125     ,  3.45833333])

In [0]:
def first_rpt(M):
  new_array=np.array(M)
  for i in range(len(M)):
    new_array[i]=M[0]
  return new_array

In [98]:
my_matrix=np.array([[1, 2, 3, 4],[-5, -6, -7, -8],[1, 5, 2, 3]])
print(first_rpt(my_matrix))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [0]:
def matrix_sum(M):
  sum=0
  for i in range(len(M)):
    for j in range(len(M[0,:])):
      sum=sum+M[i,j]
  return sum

In [100]:
mat=np.array([[1,-1,2,-3,1,1],[-2,-2,0,1,1,-5],[1,1,1,1,-2,-1]])
print(matrix_sum(mat))

-5


In [101]:
long_list=[0.5**(i+1) for i in range(10)]
long_list

[0.5,
 0.25,
 0.125,
 0.0625,
 0.03125,
 0.015625,
 0.0078125,
 0.00390625,
 0.001953125,
 0.0009765625]

In [102]:
very_long_list=[f**i for i in range(1,100) for f in [1,2,3]]
very_long_list

[1,
 2,
 3,
 1,
 4,
 9,
 1,
 8,
 27,
 1,
 16,
 81,
 1,
 32,
 243,
 1,
 64,
 729,
 1,
 128,
 2187,
 1,
 256,
 6561,
 1,
 512,
 19683,
 1,
 1024,
 59049,
 1,
 2048,
 177147,
 1,
 4096,
 531441,
 1,
 8192,
 1594323,
 1,
 16384,
 4782969,
 1,
 32768,
 14348907,
 1,
 65536,
 43046721,
 1,
 131072,
 129140163,
 1,
 262144,
 387420489,
 1,
 524288,
 1162261467,
 1,
 1048576,
 3486784401,
 1,
 2097152,
 10460353203,
 1,
 4194304,
 31381059609,
 1,
 8388608,
 94143178827,
 1,
 16777216,
 282429536481,
 1,
 33554432,
 847288609443,
 1,
 67108864,
 2541865828329,
 1,
 134217728,
 7625597484987,
 1,
 268435456,
 22876792454961,
 1,
 536870912,
 68630377364883,
 1,
 1073741824,
 205891132094649,
 1,
 2147483648,
 617673396283947,
 1,
 4294967296,
 1853020188851841,
 1,
 8589934592,
 5559060566555523,
 1,
 17179869184,
 16677181699666569,
 1,
 34359738368,
 50031545098999707,
 1,
 68719476736,
 150094635296999121,
 1,
 137438953472,
 450283905890997363,
 1,
 274877906944,
 1350851717672992089,
 1,
 